import 'dotenv/config';
import { createWalletClient, http, publicActions } from 'viem';
import { sepolia } from 'viem/chains';
import { privateKeyToAccount } from 'viem/accounts';

// Placeholder ABI and Bytecode - In a real setup, these come from `solc` or Hardhat output
const ABI = [
    {
        "inputs": [
            { "internalType": "address", "name": "initialOwner", "type": "address" },
            { "internalType": "address", "name": "_vendorWallet", "type": "address" }
        ],
        "stateMutability": "nonpayable",
        "type": "constructor"
    }
] as const;

// IMPORTANT: This is truncated/mock bytecode. 
// You must replace this with the actual bytecode generated by `solc` or `hardhat compile` for DigitalTwin.sol
const BYTECODE = "0x608060405234801561001057600080fd5b5061...";

async function main() {
    // 1. Configure Client
    const privateKey = process.env.PRIVATE_KEY as `0x${string}`;
    if (!privateKey) {
        console.warn("No PRIVATE_KEY found in .env, using test account...");
    }

    const account = privateKeyToAccount(privateKey || '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80');

    const client = createWalletClient({
        account,
        chain: sepolia,
        transport: http()
    }).extend(publicActions);

    console.log(`Deploying contract from account: ${account.address}`);

    // 2. Deploy Contract
    try {
        const hash = await client.deployContract({
            abi: ABI,
            account,
            bytecode: BYTECODE,
            args: [account.address, account.address], // Owner, VendorWallet
        });

        console.log(`Transaction Hash: ${hash}`);

        const receipt = await client.waitForTransactionReceipt({ hash });

        console.log(`Contract deployed at: ${receipt.contractAddress}`);
    } catch (error) {
        console.error("Deployment failed:", error);
    }
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
